name: Publish a release
on: workflow_dispatch
jobs:
  publish-kotlin-libraries:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew publishToMavenLocal
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
  publish-cocoapods-libraries:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - run: pod spec lint KMPNativeCoroutinesCore.podspec
      - run: pod spec lint KMPNativeCoroutinesCombine.podspec
      - run: pod spec lint KMPNativeCoroutinesRxSwift.podspec