name: Publish a Swift release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-swift-async-await'
jobs:
  publish-cocoapods-async:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2-beta'
      - name: Publish KMPNativeCoroutinesAsync
        run: pod trunk push KMPNativeCoroutinesAsync.podspec --synchronous
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}