name: Run tests
on:
  - workflow_dispatch
env:
  XCODEBUILD_DESTINATION_IOS: platform=iOS Simulator,name=iPhone 12 Pro Max
  XCODEBUILD_DESTINATION_OSX: platform=OS X
  XCODEBUILD_DESTINATION_TVOS: platform=tvOS Simulator,name=Apple TV
  XCODEBUILD_DESTINATION_WATCHOS: platform=watchOS Simulator,name=Apple Watch Series 7 - 45mm
jobs:
  run-core-tests:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew :kmp-nativecoroutines-core:allTests
  run-combine-tests:
    runs-on: macos-11
    strategy:
      matrix:
        destination: ['IOS', 'OSX', 'TVOS', 'WATCHOS']
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - env:
          XCODEBUILD_DESTINATION: ${{ env[format('XCODEBUILD_DESTINATION_{0}', matrix.destination)] }}
        run: >-
          xcodebuild test
          -project KMPNativeCoroutines.xcodeproj
          -scheme KMPNativeCoroutinesCombineTests
          -destination "$XCODEBUILD_DESTINATION"
  run-rxswift-tests:
    runs-on: macos-11
    strategy:
      matrix:
        destination: ['IOS', 'OSX', 'TVOS', 'WATCHOS']
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - env:
          XCODEBUILD_DESTINATION: ${{ env[format('XCODEBUILD_DESTINATION_{0}', matrix.destination)] }}
        run: >-
          xcodebuild test
          -project KMPNativeCoroutines.xcodeproj
          -scheme KMPNativeCoroutinesRxSwiftTests
          -destination "$XCODEBUILD_DESTINATION"
  run-integration-tests:
    runs-on: macos-11
    strategy:
      matrix:
        destination: ['IOS', 'OSX', 'TVOS', 'WATCHOS']
        include:
          - destination: IOS
            scheme: iOS Tests
          - destination: OSX
            scheme: macOS Tests
          - destination: TVOS
            scheme: tvOS Tests
          - destination: WATCHOS
            scheme: watchOS Tests
    defaults:
      run:
        working-directory: sample
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: gradle/wrapper-validation-action@v1
      - run: pod install
      - env:
          XCODEBUILD_DESTINATION: ${{ env[format('XCODEBUILD_DESTINATION_{0}', matrix.destination)] }}
          XCODEBUILD_SCHEME: ${{ matrix.scheme }}
        run: >-
          xcodebuild test
          -workspace Sample.xcworkspace
          -scheme "$XCODEBUILD_SCHEME"
          -destination "$XCODEBUILD_DESTINATION"
