name: Run tests
on:
  - workflow_dispatch
env:
  XCODEBUILD_DESTINATION_iOS: platform=iOS Simulator,name=iPhone 12 Pro Max
  XCODEBUILD_DESTINATION_macOS: platform=OS X
  XCODEBUILD_DESTINATION_tvOS: platform=tvOS Simulator,name=Apple TV
  XCODEBUILD_DESTINATION_watchOS: platform=watchOS Simulator,name=Apple Watch Series 7 - 45mm
jobs:
  run-core-tests:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew :kmp-nativecoroutines-core:allTests
  run-combine-tests:
    runs-on: macos-11
    strategy:
      matrix:
        destination: ['iOS', 'macOS', 'tvOS', 'watchOS']
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - env:
          XCODEBUILD_DESTINATION: ${{ env[format('XCODEBUILD_DESTINATION_{0}', matrix.destination)] }}
        run: >-
          xcodebuild test
          -project KMPNativeCoroutines.xcodeproj
          -scheme KMPNativeCoroutinesCombine
          -destination "$XCODEBUILD_DESTINATION"
  run-rxswift-tests:
    runs-on: macos-11
    strategy:
      matrix:
        destination: ['iOS', 'macOS', 'tvOS', 'watchOS']
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - env:
          XCODEBUILD_DESTINATION: ${{ env[format('XCODEBUILD_DESTINATION_{0}', matrix.destination)] }}
        run: >-
          xcodebuild test
          -project KMPNativeCoroutines.xcodeproj
          -scheme KMPNativeCoroutinesRxSwift
          -destination "$XCODEBUILD_DESTINATION"
  run-integration-tests:
    runs-on: macos-11
    strategy:
      matrix:
        destination: ['iOS', 'macOS', 'tvOS', 'watchOS']
        include:
          - destination: iOS
            scheme: iOS Tests
          - destination: macOS
            scheme: macOS Tests
          - destination: tvOS
            scheme: tvOS Tests
          - destination: watchOS
            scheme: watchOS Tests
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: gradle/wrapper-validation-action@v1
      - working-directory: sample
        run: pod install
      - env:
          XCODEBUILD_DESTINATION: ${{ env[format('XCODEBUILD_DESTINATION_{0}', matrix.destination)] }}
          XCODEBUILD_SCHEME: ${{ matrix.scheme }}
        working-directory: sample
        run: >-
          xcodebuild test
          -workspace Sample.xcworkspace
          -scheme "$XCODEBUILD_SCHEME"
          -destination "$XCODEBUILD_DESTINATION"
